# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: empty_lines, no_empty_lines
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

Style/Documentation:
  Exclude:
    - 'config/**/*'
    - 'db/migrate/*'

# Cop supports --auto-correct.
Style/ExpandPathArguments:
  Exclude:
    - 'bin/bundle'
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/setup'
    - 'bin/update'
    - 'spec/rails_helper.rb'

Style/MixinUsage:
  Exclude:
    - bin/**/*

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Exclude:
    - 'db/schema.rb'

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 120
  Exclude:
  - 'db/schema.rb'
  - spec/rails_helper.rb
  - 'spec/factories/*'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/**/*'

Metrics/BlockLength:
  Exclude:
    - 'db/schema.rb'
    - spec/**/*

Style/NumericLiterals:
  Exclude:
    - db/schema.rb
    - db/seeds.rb

Style/StderrPuts:
  Exclude:
    - bin/yarn

Metrics/MethodLength:
  Exclude:
    - app/controllers/graphql_controller.rb
